<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Additional Compiled Classes
    |--------------------------------------------------------------------------
    |
    | Here you may specify additional classes to include in the compiled file
    | generated by the `artisan optimize` command. These should be classes
    | that are included on basically every request into the application.
    |
    */

    'files' => [
        //
    ],

    /*
    |--------------------------------------------------------------------------
    | Compiled File Providers
    |--------------------------------------------------------------------------
    |
    | Here you may list service providers which define a "compiles" function
    | that returns additional files that should be compiled, providing an
    | easy way to get common files from any packages you are utilizing.
    |
    */

    'providers' => [
        \PN\Assets\Providers\AssetServiceProvider::class,
        \PN\BuildOffs\Providers\BuildOffServiceProvider::class,
        \PN\Forum\Providers\ForumServiceProvider::class,
        \PN\Media\Providers\ImageServiceProvider::class,
        \PN\Media\Providers\ScreenshotServiceProvider::class,
        \PN\Pages\Providers\PageServiceProvider::class,
        \PN\Resources\Providers\ResourceServiceProvider::class,
        \PN\Social\Providers\CommentServiceProvider::class,
        \PN\Social\Providers\LikeServiceProvider::class,
        \PN\Social\Providers\NotificationServiceProvider::class,
        \PN\Tracking\Providers\TrackingServiceProvider::class,
        \PN\Users\Providers\UserServiceProvider::class,
    ],

];
